sudo: true
cache: pip
language: python

python:
  - "3.7-dev"

branches:
  only:
    - dev

install:
  - pip install -r requirements.txt

before_script:
  - cd src
  - bin/installme.py
  - ./manage.py makemigrations
  - ./manage.py migrate

script:
  - coverage run --source=castic runtests.py --keepdb