version: "3"
services:
   web:
      image: zoerb/castic:0.1
      deploy:
         replicas: 1
         resources: 
            limits:
               cpus: "0.1"
               memory: 60M
         restart_policy:
            condition: on-failure
      ports:
         - "8000:8000"
      networks:
         - webnet
networks:
   webnet:
