# Generated by Django 2.1.7 on 2019-02-22 21:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='repositories',
            fields=[
                ('name', models.CharField(max_length=16)),
                ('absolPath', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('diskSpace', models.CharField(max_length=16)),
                ('lastUpdate', models.DateTimeField(default=django.utils.timezone.now)),
                ('health', models.IntegerField()),
            ],
        ),
    ]
