# Generated by Django 2.1.7 on 2019-02-24 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('repositories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='snapshots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshotID', models.CharField(max_length=8)),
                ('created', models.DateTimeField()),
                ('backupedPath', models.CharField(max_length=32)),
                ('host', models.CharField(max_length=32)),
                ('absolPath', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repositories.repositories')),
            ],
        ),
    ]
