# Generated by Django 2.1.7 on 2019-02-24 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snapshots', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snapshots',
            name='absolPath',
        ),
        migrations.DeleteModel(
            name='snapshots',
        ),
    ]
