# Generated by Django 2.1.5 on 2019-02-10 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='repositories',
            fields=[
                ('name', models.CharField(max_length=16)),
                ('absolPath', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('diskSpace', models.CharField(max_length=8)),
                ('lastUpdate', models.DateField()),
                ('health', models.IntegerField(max_length=2)),
            ],
        ),
    ]
