# Generated by Django 2.1.7 on 2019-02-18 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20190210_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repositories',
            name='lastUpdate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
