# Generated by Django 2.1.5 on 2019-02-10 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20190210_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repositories',
            name='diskSpace',
            field=models.CharField(max_length=16),
        ),
    ]
