# Generated by Django 2.1.7 on 2019-02-18 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20190218_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repositories',
            name='lastUpdate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
