# Generated by Django 2.1.7 on 2019-02-18 16:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20190218_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repositories',
            name='lastUpdate',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 18, 16, 52, 17, 155636)),
        ),
    ]
