# Generated by Django 2.1.7 on 2019-02-18 16:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_auto_20190218_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repositories',
            name='lastUpdate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
